<?php
declare(strict_types = 1);

namespace App\Core\Models;


use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{

    protected function bootIfNotBooted()
    {
        static::addGlobalScope('deleted', function(Builder $builder) {
            $builder->where('deleted', '=', 0);
        });
        parent::bootIfNotBooted(); // TODO: Change the autogenerated stub
    }

}
