<?php
    namespace App\Http\FormRequest;

    class OrderPostFormRequest extends AbstractFormRequest
    {

        public function ajax()
        {
            return parent::ajax(); // TODO: Change the autogenerated stub
        }

        public function rules()
        {
            return [
                "productId"        => [
                    "required" ,
                ] ,
                "OrderName"        => [
                    "required" ,
                ] ,
                "orderEmail"       => [
                    "required" ,
                    "email"
                ] ,
                "orderPhone"       => [
                    "required" ,
                    "integer" ,
                ] ,
                "orderAddress" => [
                    "string" ,
                    "required"
                ]
            ];
        }

        public function messages()
        {
            return [
                "productId.required"    => "Boş bırakılamaz" ,
                "OrderName.required"    => "Zorunlu Alan" ,
                "orderEmail.required"   => "Zorunlu Alan" ,
                "orderPhone.required"   => "Zorunlu Alan" ,
                "orderAddress.required" => "Zorunlu Alan"
            ];
        }
    }